#include "ncnn_omni/processors/whisper_log_mel.h"
#include "processors/qwen3_asr_audio_processor.h"

#include <cmath>
#include <stdexcept>
#include <vector>

void test_whisper_log_mel()
{
    constexpr double pi = 3.14159265358979323846;
    std::vector<float> samples(16000);
    for (size_t i = 0; i < samples.size(); ++i)
        samples[i] = static_cast<float>(0.25 * std::sin(2.0 * pi * 440.0 * i / 16000.0));

    ncnn_omni::WhisperLogMel frontend;
    auto result = frontend.compute(samples);
    if (!result) throw std::runtime_error(result.error());
    if (result.value().mel_bins != 128 || result.value().frames != 100)
        throw std::runtime_error("unexpected Log-Mel shape");
    for (float value : result.value().values) {
        if (!std::isfinite(value)) throw std::runtime_error("non-finite Log-Mel value");
    }

    struct Expected { int mel; int frame; float value; };
    // Values generated by Transformers WhisperFeatureExtractor's NumPy path.
    const Expected expected[] = {
        {0, 0, 0.757004559f}, {10, 0, 0.8352957964f},
        {20, 0, 1.179783583f}, {20, 10, 1.136878133f},
        {30, 33, -0.6651608944f}, {127, 99, -0.6651608944f}};
    for (const auto& item : expected) {
        const float actual = result.value().values[static_cast<size_t>(item.mel * 100 + item.frame)];
        if (std::abs(actual - item.value) > 3e-5f)
            throw std::runtime_error("Whisper Log-Mel differs from Transformers reference");
    }

    // WhisperFeatureExtractor does not pad a partial final hop. Centered STFT
    // yields floor(samples / hop) frames after removing its final frame.
    samples.push_back(0.f);
    auto partial_hop = frontend.compute(samples);
    if (!partial_hop) throw std::runtime_error(partial_hop.error());
    if (partial_hop.value().frames != 100)
        throw std::runtime_error("partial-hop Log-Mel shape differs from Transformers");

    const auto canonical = ncnn_omni::Qwen3AsrAudioProcessor::prepare_samples(samples);
    if (canonical.size() != 16160)
        throw std::runtime_error("Qwen3-ASR final-hop padding length is incorrect");
    for (size_t i = 0; i < samples.size(); ++i) {
        if (canonical[i] != samples[i])
            throw std::runtime_error("Qwen3-ASR final-hop padding changed an original sample");
    }
    for (size_t i = samples.size(); i < canonical.size(); ++i) {
        if (canonical[i] != 0.f)
            throw std::runtime_error("Qwen3-ASR final-hop padding is not zero");
    }

    ncnn_omni::AudioBuffer wrong_format;
    wrong_format.samples = {0.f};
    wrong_format.sample_rate = 8000;
    wrong_format.channels = 1;
    ncnn_omni::Qwen3AsrAudioProcessor processor;
    if (processor.process(wrong_format))
        throw std::runtime_error("Qwen3-ASR audio processor accepted 8 kHz PCM");
}
